### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by lbelzile** [TeemuSailynoja/simultaneous-confidence-bands#1]
Thanks for providing the code to implement your paper, which I really like. Unfortunately, without a license, the code is unusable and cannot be adapted.

> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

I already emailed the corresponding author requesting for this, but would ask you to consider again making your code available. Many thanks in advance for your consideration @TeemuSailynoja @avehtari @paul-buerkner

**Comment by TeemuSailynoja** [comment]
Thank you for pointing this oversight out! I have added a licence to the repository, as our intention indeed is to promote open science.
I'm terribly sorry for not replying to your email sooner. I'm very thankful that you posted this issue to get my attention.
